Repository OmokNoonE/PPM-frontend, pull requests merged in 2024-05, with the labels that each got.

#4 [PR] v-model 사용가능하게 수정
  src/components/MaterialInput.vue
Labels: feature

#10 [PR] Dashboard 화면 구현
  src/views/Dashboard2.vue
  src/views/columngraph.vue
  src/views/gaugegraph.vue
  src/views/linegraph.vue
  src/views/piegraph.vue
Labels: UI, feature, frontend

#11 [PR] 로그인, 로그아웃, 토큰 저장 화면 및 기능 구현
  src/axios/axios-instance.js
  src/examples/Sidenav/SidenavList.vue
  src/main.js
  src/router/index.js
  src/services/auth.js
  src/store/index.js
  src/views/SignIn.vue
Labels: UI, feature, frontend

#14 [PR] 프로젝트 목록 UI 개발
  src/examples/Sidenav/SidenavCreateProjectModal.vue
  src/examples/Sidenav/SidenavList.vue
Labels: UI, feature, frontend

#15 [PR] 요구사항 목록 조회, 등록, 수정, 삭제 화면 구현
  src/examples/Footer.vue
  src/examples/Sidenav/SidenavList.vue
  src/router/index.js
  src/views/ModifyRequirement.vue
  src/views/RegisterRequirement.vue
  src/views/Requirements.vue
Labels: feature, frontend

#17 [PR] 프로젝트 구성원 화면 기능 구현
  package.json
  src/main.js
  src/store/projectMemberStore.js
  src/views/Tables.vue
  src/views/components/AddProjectMemberCard.vue
  src/views/components/ModifyProjectMemberRoleCard.vue
Labels: UI, feature, frontend

#16 [PR] 프로젝트 목록 조회/생성 UI, 기능 구현
  src/examples/Sidenav/SidenavCreateProjectModal.vue
  src/examples/Sidenav/SidenavList.vue
  src/services/auth.js
  src/store/index.js
Labels: UI, feature, frontend

#18 [PR] SideNav Table 경로 수정 및 Requirements 코드 일부 수정
  src/examples/Sidenav/SidenavCollapse.vue
  src/examples/Sidenav/SidenavList.vue
  src/router/index.js
Labels: feature, fix, frontend

#20 #6 [PR] 일정 상세보기 화면 API 요청 개발
  src/components/MaterialSchedule.vue
Labels: UI, feature

#24 [PR] 일정 페이지의 요구사항 검색 및 등록 모달 구현
  src/views/CreateSchedule.vue
Labels: UI, feature

#25 [PR] 프로젝트 구성원 화면 일부 기능 제거 및 개선
  src/store/projectMemberStore.js
  src/views/Tables.vue
  src/views/components/AddProjectMemberCard.vue
Labels: UI, feature, frontend, refactor

#26 [PR] 알림 화면 기능 구현
  package.json
  src/components/MaterialSnackbar.vue
  src/store/index.js
  src/store/notifications.js
  src/views/Notifications.vue
Labels: UI, feature, frontend, style

#27 [PR] 알림 화면 수정
  src/store/index.js
  src/views/Notifications.vue
Labels: UI, frontend, style

#30 [PR] store 분리와 axios 사용 변경
  src/store/index.js
  src/store/login.js
  src/store/notifications.js
  src/store/projectMemberStore.js
  src/views/ModifyRequirement.vue
  src/views/RegisterRequirement.vue
  src/views/Requirements.vue
Labels: feature, refactor

#33 [PR] Router 설정과 사용하지 않는 View 파일 삭제
  package.json
  src/router/index.js
  src/views/Dashboard.vue
  src/views/Dashboard2.vue
  src/views/Notifications.vue
  src/views/Profile.vue
  src/views/ProjectMember.vue
  src/views/Requirements.vue
  src/views/Rtl.vue
  src/views/SignUp.vue
  src/views/components/ColumnGraph.vue
  src/views/components/GaugeGraph.vue
  src/views/components/LineGraph.vue
  src/views/components/ModifyRequirement.vue
  src/views/components/PieGraph.vue
Labels: feature, fix, remove, rename

#35 [PR] [HotFix] login store 분리 후 store getter 부분 수정
  src/router/index.js
  src/services/auth.js
  src/store/login.js
Labels: fix

#37 #36 [fix] 사이드바 네이비게이션 라우터 경로 수정
  src/examples/Sidenav/SidenavList.vue
  src/examples/Sidenav/index.vue
  src/router/index.js
Labels: UI, bug, frontend

#38 [PR] 일정 화면 구현
  package.json
  src/components/Handsontable.vue
  src/components/MaterialSchedule.vue
  src/components/PermissionModal.vue
  src/components/RequirementModal.vue
  src/components/StakeholderModal.vue
  src/components/TaskModal.vue
  src/main.js
  src/router/index.js
  src/shims-vue.d.ts
  src/utils/constants.ts
  src/utils/hooks-callbacks.ts
  src/views/Billing.vue
  src/views/CreateSchedule.vue
  src/views/ScheduleSheet.vue
  src/views/components/AddProjectMemberToScheduleModal.vue
  tsconfig.json
  vue.config.js
Labels: UI, feature, frontend

#39 [PR] 일정 페이지 라우터 변경 및 파일 이름 변경
  package.json
  src/examples/Sidenav/SidenavList.vue
  src/router/index.js
  src/views/Schedules.vue
Labels: fix, rename

#41 [PR] vue 파일 수정 시 서버 종료되는 현상 해결 (HMR 오류)
  vue.config.js
Labels: fix
