Repository OmokNoonE/PPM-frontend, pull requests merged in 2024-06, with the labels that each got.

#43 [PR] 일정 화면 수정
  src/components/MaterialSchedule.vue
  src/components/PermissionModal.vue
  src/components/RequirementModal.vue
  src/components/TaskModal.vue
  src/views/CreateSchedule.vue
  src/views/ScheduleSheet.vue
  src/views/components/AddProjectMemberToScheduleModal.vue
Labels: UI, bug, feature, fix, frontend, remove

#45 [PR] 금주, 차주 일정 요약 페이지
  src/router/index.js
  src/views/Todo.vue
Labels: UI, feature, frontend

#46 [PR] 알림 화면 개선
  src/router/index.js
  src/store/notifications.js
  src/views/Notifications.vue
Labels: UI, feature, frontend

#49 [PR] 구성원 화면 재구성 및 기능 오류 제거
  src/store/projectMember.js
  src/views/ProjectMember.vue
  src/views/components/AddProjectMemberCard.vue
  src/views/components/ModifyProjectMemberRoleCard.vue
Labels: UI, feature, fix

#47 [refactor] 요구 사항 화면 UI 개선
  src/views/Requirements.vue
Labels: UI, frontend

#52 [PR] 로그인 시, 전역으로 사용되는 변수 가져오기
  src/router/index.js
  src/services/auth.js
  src/store/login.js
  src/views/SignIn.vue
Labels: feature

#54 [fix] notification 화면 API 통신을 위한 수정
  src/store/notifications.js
  src/views/Notifications.vue
Labels: fix, frontend

#55 [PR] Notification 삭제 구현
  src/views/Notifications.vue
Labels: feature, frontend

#56 [PR] Store로 관리되어야 할 변수들로 변경
  src/components/MaterialSchedule.vue
  src/components/StakeholderModal.vue
  src/examples/Sidenav/SidenavCreateProjectModal.vue
  src/router/index.js
  src/services/auth.js
  src/store/projectMember.js
  src/views/CreateSchedule.vue
  src/views/Notifications.vue
  src/views/ProjectMember.vue
  src/views/Requirements.vue
  src/views/ScheduleSheet.vue
  src/views/SignIn.vue
  src/views/Todo.vue
  src/views/components/AddProjectMemberCard.vue
  src/views/components/AddProjectMemberToScheduleModal.vue
  src/views/components/ColumnGraph.vue
  src/views/components/GaugeGraph.vue
  src/views/components/LineGraph.vue
  src/views/components/ModifyProjectMemberRoleCard.vue
  src/views/components/PieGraph.vue
Labels: refactor

#58 [PR] 화면에 에러메세지가 출력되는 부분 수정
  src/store/notifications.js
  src/views/Notifications.vue
Labels: fix, frontend

#59 [PR] 1차 QA 완료
  package.json
  src/App.vue
  src/assets/img/ppm-logo-maerong.png
  src/assets/img/ppm-logo-pink-blue.png
  src/axios/axios-instance.js
  src/components/MaterialSchedule.vue
  src/examples/Configurator.vue
  src/examples/Navbars/Navbar.vue
  src/examples/PageLayout/Navbar.vue
  src/examples/Sidenav/SidenavCreateProjectModal.vue
  src/examples/Sidenav/SidenavList.vue
  src/examples/Sidenav/index.vue
  src/main.js
  src/router/index.js
  src/services/auth.js
  src/store/index.js
  src/store/login.js
  src/store/notifications.js
  src/store/projectMember.js
  src/views/CreateSchedule.vue
  src/views/Dashboard.vue
  src/views/Notifications.vue
  src/views/ProjectMember.vue
  src/views/RegisterRequirement.vue
  src/views/Requirements.vue
  src/views/ScheduleSheet.vue
  src/views/Schedules.vue
  src/views/SignIn.vue
  src/views/Todo.vue
  src/views/components/AddProjectMemberCard.vue
  src/views/components/AddProjectMemberToScheduleModal.vue
  src/views/components/ColumnGraph.vue
  src/views/components/GaugeGraph.vue
  src/views/components/LineGraph.vue
  src/views/components/ModifyProjectMemberRoleCard.vue
  src/views/components/ModifyRequirement.vue
  src/views/components/PieGraph.vue
  src/views/components/ProjectModal.vue
Labels: UI, feature, fix, frontend, refactor, remove, rename, style, test

#60 [Release] PPM v.1.0
  package.json
  public/favicon.png
  public/index.html
  src/App.vue
  src/assets/img/ppm-logo-maerong.png
  src/assets/img/ppm-logo-pink-blue.png
  src/axios/axios-instance.js
  src/components/Handsontable.vue
  src/components/MaterialInput.vue
  src/components/MaterialSchedule.vue
  src/components/MaterialSnackbar.vue
  src/components/StakeholderModal.vue
  src/examples/Configurator.vue
  src/examples/Footer.vue
  src/examples/Navbars/Navbar.vue
  src/examples/PageLayout/Navbar.vue
  src/examples/Sidenav/SidenavCollapse.vue
  src/examples/Sidenav/SidenavList.vue
  src/examples/Sidenav/index.vue
  src/main.js
  src/router/index.js
  src/services/auth.js
  src/shims-vue.d.ts
  src/store/index.js
  src/store/login.js
  src/store/notifications.js
  src/store/projectMember.js
  src/utils/constants.ts
  src/utils/hooks-callbacks.ts
  src/views/Billing.vue
  src/views/CreateSchedule.vue
  src/views/Dashboard.vue
  src/views/Notifications.vue
  src/views/Profile.vue
  src/views/ProjectMember.vue
  src/views/RegisterRequirement.vue
  src/views/Requirements.vue
  src/views/Rtl.vue
  src/views/ScheduleSheet.vue
  src/views/Schedules.vue
  src/views/SignIn.vue
  src/views/SignUp.vue
  src/views/Tables.vue
  src/views/Todo.vue
  src/views/components/AddProjectMemberCard.vue
  src/views/components/AddProjectMemberToScheduleModal.vue
  src/views/components/ColumnGraph.vue
  src/views/components/GaugeGraph.vue
  src/views/components/LineGraph.vue
  src/views/components/ModifyProjectMemberRoleCard.vue
  src/views/components/ModifyRequirement.vue
  src/views/components/PieGraph.vue
  src/views/components/ProjectModal.vue
  tsconfig.json
  vue.config.js
Labels: UI, feature, fix, frontend, refactor, remove, rename, style

#62 [HotFix] 서버 URL 주입, 외부 IP 허용
  src/axios/axios-instance.js
  src/main.js
  vue.config.js
Labels: fix

#65 [PR] 2차 QA 전 main 수정사항 develop 반영
  manifests/kustomization.yaml
  public/index.html
  src/axios/axios-instance.js
  src/main.js
  src/router/index.js
  src/views/Dashboard.vue
  src/views/Notifications.vue
  vue.config.js
Labels: frontend

#66 [fix] 일정 상세보기 시, 요구사항을 불러오지 못하는 에러 해결
  src/views/Calendar.vue
Labels: fix

#67 [PR] 일정 2차 QA 및 수정
  src/components/MaterialSchedule.vue
  src/views/CreateSchedule.vue
  src/views/ScheduleSheet.vue
Labels: UI, feature, fix, frontend

#68 [PR] 일정 달력 페이지 구현
  package.json
  src/event-utils.js
  src/router/index.js
  src/views/Calendar.vue
  src/views/CreateSchedule.vue
  src/views/ScheduleSheet.vue
Labels: UI, feature, fix, frontend

#71 [PR] 관리자용 페이지 만들기
  src/components/MaterialInput.vue
  src/examples/Sidenav/SidenavList.vue
  src/router/index.js
  src/services/auth.js
  src/store/login.js
  src/views/AdminEmployee.vue
  src/views/AdminProject.vue
Labels: UI, feature

#73 [PR] 일정 페이지 UI 피드백 반영
  src/components/MaterialInput.vue
  src/components/MaterialSchedule.vue
  src/views/CreateSchedule.vue
Labels: UI

#74 [PR] 일정 상세 수정
  src/components/MaterialInput.vue
  src/components/MaterialSchedule.vue
  src/views/Calendar.vue
Labels: UI, feature, fix, frontend

#77 [PR] 대시보드 탭 각 그래프 타이틀 추가
  src/views/Dashboard.vue
  src/views/components/ColumnGraph.vue
  src/views/components/GaugeGraph.vue
  src/views/components/LineGraph.vue
  src/views/components/PieGraph.vue
Labels: UI, frontend

#79 [PR] 피드백 이후 UI 수정
  src/examples/Sidenav/SidenavCollapse.vue
  src/examples/Sidenav/SidenavList.vue
  src/views/Calendar.vue
  src/views/ProjectMember.vue
  src/views/RegisterRequirement.vue
  src/views/Requirements.vue
  src/views/ScheduleSheet.vue
  src/views/components/ModifyRequirement.vue
Labels: UI, feature

#80 [Release] PPM front v.1.0.6
  package.json
  src/components/MaterialInput.vue
  src/components/MaterialSchedule.vue
  src/event-utils.js
  src/examples/Sidenav/SidenavCollapse.vue
  src/examples/Sidenav/SidenavList.vue
  src/router/index.js
  src/services/auth.js
  src/store/index.js
  src/store/login.js
  src/views/AdminEmployee.vue
  src/views/AdminProject.vue
  src/views/Calendar.vue
  src/views/CreateSchedule.vue
  src/views/Dashboard.vue
  src/views/Notifications.vue
  src/views/ProjectMember.vue
  src/views/RegisterRequirement.vue
  src/views/Requirements.vue
  src/views/ScheduleSheet.vue
  src/views/Todo.vue
  src/views/components/ColumnGraph.vue
  src/views/components/GaugeGraph.vue
  src/views/components/LineGraph.vue
  src/views/components/ModifyRequirement.vue
  src/views/components/PieGraph.vue
Labels: UI, feature, fix, frontend, refactor, style

#81 [PR]markAsRead 반영되도록 수정
  src/views/Notifications.vue
Labels: fix, frontend

#82 [PR] 알림, 일정, 프로젝트 UI 수정
  src/assets/img/omoknoone.gif
  src/examples/Configurator.vue
  src/store/index.js
  src/views/Notifications.vue
  src/views/ScheduleSheet.vue
  src/views/components/ProjectModal.vue
Labels: UI, feature

#84 [Release] PPM front v.1.1.0
  manifests/kustomization.yaml
  src/assets/img/omoknoone.gif
  src/examples/Configurator.vue
  src/store/index.js
  src/views/Notifications.vue
  src/views/ScheduleSheet.vue
  src/views/components/ProjectModal.vue
Labels: UI, feature, frontend

#85 [Release] PPM front v.1.1.1
  src/views/AdminEmployee.vue
Labels: fix
